# Dictionnaire pour traduire les descriptions météorologiques en français
weather_dict = {
    'thunderstorm with light rain': 'orage avec pluie légère',
    'thunderstorm with rain': 'orage avec pluie',
    'thunderstorm with heavy rain': 'orage avec fortes pluies',
    'light thunderstorm': 'orage léger',
    'thunderstorm': 'orage',
    'heavy thunderstorm': 'orage violent',
    'ragged thunderstorm': 'orage déchiqueté',
    'thunderstorm with light drizzle': 'orage avec légère bruine',
    'thunderstorm with drizzle': 'orage avec bruine',
    'thunderstorm with heavy drizzle': 'orage avec forte bruine',
    'light intensity drizzle': 'bruine légère',
    'drizzle': 'bruine',
    'heavy intensity drizzle': 'forte bruine',
    'light intensity drizzle rain': 'pluie et bruine légère',
    'drizzle rain': 'pluie et bruine',
    'heavy intensity drizzle rain': 'pluie et forte bruine',
    'shower rain and drizzle': 'averses de pluie et bruine',
    'heavy shower rain and drizzle': 'fortes averses de pluie et bruine',
    'shower drizzle': 'averses de bruine',
    'light rain': 'pluie légère',
    'moderate rain': 'pluie modérée',
    'heavy intensity rain': 'fortes pluies',
    'very heavy rain': 'pluies très fortes',
    'extreme rain': 'pluies extrêmes',
    'freezing rain': 'pluies verglaçantes',
    'light intensity shower rain': 'averses de pluie légère',
    'shower rain': 'averses de pluie',
    'heavy intensity shower rain': 'fortes averses de pluie',
    'ragged shower rain': 'averses de pluie intermittentes',
    'light snow': 'neige légère',
    'snow': 'neige',
    'heavy snow': 'fortes chutes de neige',
    'sleet': 'pluie verglaçante',
    'light shower sleet': 'averses de pluie verglaçante légères',
    'shower sleet': 'averses de pluie verglaçante',
    'light rain and snow': 'pluie et neige légères',
    'rain and snow': 'pluie et neige',
    'light shower snow': 'averses de neige légères',
    'shower snow': 'averses de neige',
    'heavy shower snow': 'fortes averses de neige',
    'mist': 'brume',
    'smoke': 'fumée',
    'haze': 'brume sèche',
    'sand/dust whirls': 'tourbillons de sable / poussière',
    'fog': 'brouillard',
    'sand': 'sable',
    'dust': 'poussière',
    'volcanic ash': 'cendres volcaniques',
    'squalls': 'rafales de vent',
    'tornado': 'tornade',
    'clear sky': 'ciel dégagé',
    'few clouds': 'quelques nuages',
    'scattered clouds': 'nuages épars',
    'broken clouds': 'nuages fragmentés',
    'overcast clouds': 'nuageux',
    'mist': 'brume',
    'smoke': 'fumée',
    'haze': 'brume sèche',
    'sand': 'sable',
    'dust': 'poussière',
    'fog': 'brouillard',
    'squalls': 'rafales de vent',
    'tornado': 'tornade',
    'thunderstorm with light rain': 'orage avec pluie légère',
    'thunderstorm with rain': 'orage avec pluie',
    'thunderstorm with heavy rain': 'orage avec fortes pluies',
    'light thunderstorm': 'orage léger',
    'thunderstorm': 'orage',
    'heavy thunderstorm': 'orage violent',
    'ragged thunderstorm': 'orage déchiqueté',
    'thunderstorm with light drizzle': 'orage avec légère bruine',
    'thunderstorm with drizzle': 'orage avec bruine',
    'thunderstorm with heavy drizzle': 'orage avec fortes précipitations',
    'light intensity drizzle': 'légère bruine',
    'drizzle': 'bruine',
    'heavy intensity drizzle': 'forte bruine',
    'light intensity drizzle rain': 'pluie légère',
    'drizzle rain': 'pluie',
    'heavy intensity drizzle rain': 'pluie forte',
    'shower rain and drizzle': 'pluie et bruine',
    'heavy shower rain and drizzle': 'forte pluie et bruine',
    'shower drizzle': 'pluie fine',
    'light rain': 'légère pluie',
    'moderate rain': 'pluie modérée',
    'heavy intensity rain': 'fortes précipitations',
    'very heavy rain': 'pluie très forte',
    'extreme rain': 'pluie extrême',
    'freezing rain': 'pluie verglaçante',
    'light intensity shower rain': 'averse légère',
    'shower rain': 'averse',
    'heavy intensity shower rain': 'averse forte',
    'ragged shower rain': 'averse orageuse',
    'light snow': 'neige légère',
    'snow': 'neige',
    'heavy snow': 'neige forte',
    'sleet': 'neige fondue',
    'light shower sleet': 'faibles averses de neige fondue',
    'shower sleet': 'averses de neige fondue',
    'light rain and snow': 'neige et pluie légère',
    'rain and snow': 'neige et pluie',
    'light shower snow': 'faibles averses de neige',
    'shower snow': 'averses de neige',
    'heavy shower snow': 'fortes averses de neige',
    'mist': 'brume',
    'smoke': 'fumée',
    'haze': 'brume sèche',
    'sand/dust whirls': 'tourbillons de sable/poussière',
    'fog': 'brouillard',
    'sand': 'sable',
    'dust': 'poussière',
    'volcanic ash': 'cendres volcaniques',
    'squalls': 'rafales de vent',
    'tornado': 'tornade',
    'clear sky': 'ciel dégagé',
    'few clouds: 11-25%': 'quelques nuages: 11-25%',
    'scattered clouds: 25-50%': 'nuages épars: 25-50%',
    'broken clouds: 51-84%': 'nuages brisés: 51-84%',
    'overcast clouds: 85-100%': 'nuages couverts: 85-100%'
    }